#!/usr/bin/env node
// One-off migration: copies every photo currently listed by the old
// Infomaniak photos-list.php into the new R2 bucket, and seeds D1 with a
// matching guests/photos/folders rows so quotas and the admin's folder
// browser both start out consistent with what's already there.
//
// Requires `wrangler` (already a devDependency here) logged in
// (`npx wrangler login`) with access to the D1 database and R2 bucket named
// in wrangler.toml — it shells out to `wrangler r2 object put` and writes a
// SQL file you run yourself via `wrangler d1 execute` (see the printed
// instructions at the end), rather than mutating D1 automatically, so you
// get a chance to review it first.
//
// Usage: node migrate.mjs
//   (run from inside cloudflare/, after `npm install` there)

import { execFileSync } from 'node:child_process'
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

// TODO: replace with your bucket name if you changed it from wrangler.toml's
// default, and confirm this still points at your actual Infomaniak folder.
const R2_BUCKET = 'l-et-m-photos'
const OLD_PHOTOS_LIST_URL = 'https://ralbasini.ch/l-et-m/photos-list.php'
const OLD_IMG_BASE = 'https://ralbasini.ch/l-et-m/img/'
const SEED_SQL_PATH = './migrate-seed.sql'

function sqlString (value) {
  return `'${String(value).replace(/'/g, "''")}'`
}

async function main () {
  console.log(`Fetching photo list from ${OLD_PHOTOS_LIST_URL} ...`)
  const res = await fetch(OLD_PHOTOS_LIST_URL)
  if (!res.ok) throw new Error(`photos-list.php returned ${res.status}`)
  const entries = await res.json()
  if (!Array.isArray(entries)) throw new Error('Unexpected photos-list.php response shape')
  console.log(`Found ${entries.length} photo(s).`)

  const tmpDir = mkdtempSync(join(tmpdir(), 'l-et-m-migrate-'))
  const guestNames = new Set()
  const sqlLines = [
    '-- Generated by migrate.mjs — review before running:',
    '--   wrangler d1 execute l-et-m --remote --file migrate-seed.sql',
    '',
  ]

  let index = 0
  for (const entry of entries) {
    index += 1
    const file = typeof entry === 'string' ? entry : entry.file
    const alt = typeof entry === 'string' ? '' : (entry.alt || '')
    const tags = typeof entry === 'string' ? [] : (entry.tags || [])

    const folder = file.includes('/') ? file.slice(0, file.lastIndexOf('/')) : ''
    const filename = file.includes('/') ? file.slice(file.lastIndexOf('/') + 1) : file
    const guestMatch = folder.match(/^Invit[ée]s\/(.+)$/)
    const guestName = guestMatch ? guestMatch[1] : null
    if (guestName) guestNames.add(guestName)

    // Download then upload, rather than piping — most reliable across
    // wrangler versions, and lets this resume-by-hand if it dies partway
    // (just re-run; `put` overwrites, it won't duplicate anything).
    const encodedPath = file.split('/').map(encodeURIComponent).join('/')
    const localPath = join(tmpDir, `photo-${index}`)
    console.log(`[${index}/${entries.length}] ${file}`)
    const photoRes = await fetch(OLD_IMG_BASE + encodedPath)
    if (!photoRes.ok) {
      console.warn(`  ! skipped, ${photoRes.status} fetching original`)
      continue
    }
    writeFileSync(localPath, Buffer.from(await photoRes.arrayBuffer()))

    execFileSync('npx', ['wrangler', 'r2', 'object', 'put', `${R2_BUCKET}/${file}`, '--file', localPath, '--remote'], {
      stdio: 'inherit',
    })
    rmSync(localPath)

    const sizeBytes = photoRes.headers.get('content-length') || 0
    sqlLines.push(
      `INSERT INTO photos (r2_key, folder, filename, size_bytes, caption) VALUES ` +
      `(${sqlString(file)}, ${sqlString(folder)}, ${sqlString(filename)}, ${sizeBytes}, ${sqlString(alt)});`
    )
    if (folder) {
      const segments = folder.split('/')
      for (let i = 1; i <= segments.length; i++) {
        sqlLines.push(`INSERT OR IGNORE INTO folders (path) VALUES (${sqlString(segments.slice(0, i).join('/'))});`)
      }
    }
    for (const tag of tags) {
      sqlLines.push(`INSERT OR IGNORE INTO tags (name) VALUES (${sqlString(tag)});`)
      sqlLines.push(
        `INSERT OR IGNORE INTO photo_tags (photo_id, tag_name) ` +
        `SELECT id, ${sqlString(tag)} FROM photos WHERE r2_key = ${sqlString(file)};`
      )
    }
  }

  sqlLines.push('', '-- Guests, so each folder\'s owner (and their upload quota) carries over:')
  for (const name of guestNames) {
    sqlLines.push(`INSERT OR IGNORE INTO guests (name) VALUES (${sqlString(name)});`)
    sqlLines.push(
      `UPDATE photos SET guest_id = (SELECT id FROM guests WHERE name = ${sqlString(name)}) ` +
      `WHERE folder = ${sqlString(`Invités/${name}`)};`
    )
  }

  writeFileSync(SEED_SQL_PATH, sqlLines.join('\n') + '\n')
  rmSync(tmpDir, { recursive: true, force: true })

  console.log(`\nAll photos copied into R2 bucket "${R2_BUCKET}".`)
  console.log(`Wrote ${SEED_SQL_PATH} — review it, then run:`)
  console.log('  npx wrangler d1 execute l-et-m --remote --file migrate-seed.sql')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
