import { isShown } from './admin-access.js'

const pages = ['mariage', 'galerie', 'photos', 'admin']
const shell = document.getElementById('app-shell')

async function initializeWeddingEmbed () {
  const themeScripts = [
    'jquery.min.js',
    'jquery.scrollex.min.js',
    'jquery.scrolly.min.js',
    'browser.min.js',
    'breakpoints.min.js',
    'util.js',
    'main.js',
  ].map((file) => `${import.meta.env.BASE_URL}mariage/assets/js/${file}`)

  // All requested at once; async = false keeps them executing in order.
  await Promise.all(themeScripts.map((src) => new Promise((resolve) => {
    const script = document.createElement('script')
    script.src = src
    script.async = false
    script.onload = resolve
    script.onerror = resolve
    document.body.appendChild(script)
  })))

  await import('./site-swipe-nav.js')
}

if (window.parent !== window) {
  if (new URLSearchParams(location.search).get('embed') === 'mariage') initializeWeddingEmbed()
} else if (shell) {
  // The menu is generated by the site-chrome plugin (vite.config.js); its
  // Mariage/Galerie/Photos links switch panels here instead of navigating.
  const nav = document.querySelector('.site-nav')
  const links = [...nav.querySelectorAll('a[data-page]')].filter((link) => pages.includes(link.dataset.page))
  const track = document.getElementById('panel-track')
  const frames = [...track.querySelectorAll('iframe[data-page]')]
  const framesByPage = new Map(frames.map((frame) => [frame.dataset.page, frame]))
  // Pages currently in the menu (admin-access.js may hide Galerie/Photos).
  // Only these are reachable with arrow keys or preloaded; a direct
  // #galerie / #photos link still opens its panel for anyone. Computed on
  // demand since the site-wide setting can arrive after the first render.
  function menuPages () {
    return pages.filter((page) => links.some((link) => link.dataset.page === page && isShown(link)))
  }

  function ensureLoaded (page) {
    const frame = framesByPage.get(page)
    if (frame && !frame.hasAttribute('src')) frame.src = frame.dataset.src
  }

  // The panel currently shown, to spot a navigation *to* Galerie.
  let shownPage = ''

  function render () {
    const requested = location.hash.slice(1)
    const page = pages.includes(requested) ? requested : 'mariage'
    const index = pages.indexOf(page)

    if (requested !== page) history.replaceState(null, '', `#${page}`)

    track.style.transform = `translate3d(-${index * 100}vw, 0, 0)`
    links.forEach((link) => {
      const active = link.dataset.page === page
      link.classList.toggle('is-current', active)
      if (active) link.setAttribute('aria-current', 'page')
      else link.removeAttribute('aria-current')
    })
    frames.forEach((frame) => {
      const active = frame.dataset.page === page
      frame.setAttribute('aria-hidden', String(!active))
      frame.tabIndex = active ? 0 : -1
    })

    // Every visit to Galerie shows the current photos: reload it if it was
    // already loaded (photos may have changed in Photos or Admin meanwhile).
    const galerieFrame = framesByPage.get('galerie')
    if (page === 'galerie' && shownPage !== 'galerie' && galerieFrame.hasAttribute('src')) {
      galerieFrame.contentWindow.location.reload()
    }
    shownPage = page
    ensureLoaded(page)
    if (page === 'galerie') ensureLoaded('mariage')
    document.body.classList.remove('is-preload')
  }

  nav.addEventListener('click', (event) => {
    const link = event.target.closest('a[data-page]')
    if (!link || !links.includes(link)) return
    event.preventDefault()
    if (location.hash !== `#${link.dataset.page}`) location.hash = link.dataset.page
  })

  // The Galerie panel is the heavy one (it lists and loads the photos), so
  // it only starts loading once the visitor shows interest — a touch, a key
  // press, or pointing at the menu — instead of on every visit. Navigating
  // to it directly still loads it (render).
  function preloadGalerie () {
    if (menuPages().includes('galerie')) ensureLoaded('galerie')
  }
  for (const type of ['pointerdown', 'touchstart', 'keydown']) {
    window.addEventListener(type, preloadGalerie, { once: true, passive: true })
  }
  nav.addEventListener('pointerover', preloadGalerie, { once: true })

  // Photos is light (no photo list), so it loads in the background once the
  // Mariage panel has settled — switching to it is then instant instead of
  // waiting on the page, its CSS and its first API call.
  function preloadPhotos () {
    if (menuPages().includes('photos')) ensureLoaded('photos')
  }
  const idle = window.requestIdleCallback || ((callback) => setTimeout(callback, 1000))
  framesByPage.get('mariage').addEventListener('load', () => idle(preloadPhotos), { once: true })

  window.addEventListener('hashchange', render)
  window.addEventListener('message', (event) => {
    if (event.origin !== location.origin || !frames.some((frame) => frame.contentWindow === event.source)) return
    const { type, page, anchor } = event.data || {}
    if (type === 'gallery-stale') {
      // Reload the (already loaded) galerie so it lists the new/removed photos.
      const gallery = framesByPage.get('galerie')
      if (gallery?.hasAttribute('src')) gallery.contentWindow.location.reload()
      return
    }
    if (type !== 'site-nav' || !pages.includes(page)) return
    if (location.hash !== `#${page}`) location.hash = page
    if (anchor) scrollPanelTo(page, anchor)
  })

  // Scroll a panel to a section of its page (e.g. "Voir les photos de tous les invités"
  // → the "La Galerie" section, below the photo header), once that panel's
  // page has loaded. The panel scrolls itself only — scrollIntoView() would
  // also try to scroll the (overflow: hidden) panel track here.
  function scrollPanelTo (page, anchor) {
    const frame = framesByPage.get(page)
    if (!frame) return
    ensureLoaded(page)
    const scroll = () => {
      const win = frame.contentWindow
      const target = win && win.document.getElementById(anchor)
      if (!target) return false
      const smooth = !window.matchMedia('(prefers-reduced-motion: reduce)').matches
      win.scrollTo({ top: target.getBoundingClientRect().top + win.scrollY, behavior: smooth ? 'smooth' : 'auto' })
      return true
    }
    if (frame.contentDocument?.readyState === 'complete' && scroll()) return
    frame.addEventListener('load', scroll, { once: true })
  }

  render()
}
